### ISSUE TITLE
Cleverbot

### ISSUE THREAD

**Issue by Esjitu** [FormalHellhound/BruhBot#1]
Add the ability to communicate with Cleverbot by @mentioning the bot.

Bonus points if the command can be triggered from anywhere in the sentence - ex. `How are you today, @BruhBot ?`, and not only `@BruhBot , how are you today?`.

**Comment by MadnessExpress** [comment]
Implemented

**Comment by MadnessExpress** [comment]
This was not to my liking and needs to be redesigned. Another problem is that the only ruby api wrappers I found were outdated and no longer work. I was using cleverbot.io, but it only allows you so many requests per day, but so far my requests have not reset.

**Comment by MadnessExpress** [comment]
I found an api wrapper, and have redesigned this. It is now working.
