### ISSUE TITLE
Change Bot's Played Game

### ISSUE THREAD

**Issue by Esjitu** [FormalHellhound/BruhBot#12]
The ability for users (perhaps restricted to specific roles) to change the 'now playing' text under the bot's name in the userlist.

Ex. `!botplay with my imouto` would display `playing with my imouto' under the bot's name.

This is a very important feature request.

**Comment by MadnessExpress** [comment]
Completed with command !game

**Comment by Esjitu** [comment]
In the event we employ a function like [issue 15](https://github.com/FormalHellhound/BruhBot/issues/15) I think maybe the command should be something besides !game. Maybe `!botgame` or `!botplay` so you know it's the command to change the bot's game, and not ask others to game with you?
