### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by Esjitu** [FormalHellhound/BruhBot#14]
Running `!quote` would output a random quote from an array of choices. 

These quotes should be configurable by the user - someone running an anime server would likely want different quotes than someone running a World of Warcraft server, for instance.

For best results, quotes should be formatted in `blockquote syntax.`

**Comment by MadnessExpress** [comment]
This was implemented with !quoteadd and !quote, but currently lacks a way to delete quotes.
