### ISSUE TITLE
Make The Bot Say Stuff

### ISSUE THREAD

**Issue by Esjitu** [FormalHellhound/BruhBot#16]
Many Discord bots allow the bot to be conversed with through a Cleverbot script, but what about having the admin make the bot say cheeky things from behind the scenes?

A role-restricted `!botsay` command could allow the admin or similarly permitted role to have the bot say specific things. This could be used for announcements or just to troll your fellow users.

**Comment by Timmooo** [comment]
To confirm, this would be a command only from a private message, not from the same channel you want them to speak in?

**Comment by Esjitu** [comment]
I hadn't thought about it too much, but it makes the most sense if it's done by PMing the bot. That way the users in the channel can't see that you're the one who told the bot to say that, and it would keep it behind the scenes. I approve.

**Comment by MadnessExpress** [comment]
Implemented with !say
