### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by Esjitu** [FormalHellhound/BruhBot#22]
The obligatory music function for a Discord bot.

I have no idea how these usually work because I've never been able to get them to. Users somehow tell the bot to play the specified song, which it does via a voice channel.

Ideally the bot would be able to accept both external links (YouTube, SoundCloud, maybe even a direct link to an MP3 via Dropbox or something) _as well as_ upload songs from the user's computer. This could either upload the file to the bot's server, or perhaps a dedicated Dropbox or similar service defined by the bot owner (in the event they don't want the bot's server getting crammed up with MP3 files). Either way, the ability to upload music directly from one's harddrive is an important distinction from sites like http://dubtrack.fm and IMO quite an essential one.

I don't want to mark this as a low priority request because it's something I consider an important feature for the bot, but I think it's also one of the harder ones to program properly and might not happen right away. Ergo, I'm tagging this as both a regular _and_ low-priority request.

**Comment by MadnessExpress** [comment]
This has been implemented.
