### ISSUE TITLE
Backend Database

### ISSUE THREAD

**Issue by Timmooo** [FormalHellhound/BruhBot#24]
Would performance be increased by the use of a backend database? 
Not overly fussy on what would be used, although most people are more familiar with mySQL - we could have one db that we can all connect to for testing. 

Particularly for features such as trivia and quotes, where there may end up being large amounts of data be used and referenced this would be a lot easier. Smaller ones like reaction faces may be easier with this. 

Related to this would be the ability to have ![module] add and ![module] remove functions to remove particular options from the database. There is a quote teh admin wants to remove !quotes remove [ref](whether this is done by a search of the db or by assigning a quote number to each one can be discussed) etc. 

Having a database set up for initial creation could make many things a lot easier, even just storing the last active state of all modules - !enable 8ball -> edit entry to be 1 for true. 

Again, open to discussion about this all but figured we can put it out here.

**Comment by MadnessExpress** [comment]
Plugins are managed in the core config.yml file. It is simply an array, and the bot iterates through the array looking for each module name in the plugins folder. I have begun using Sqlite3 with some other plugins like the quotes plugin to store the quotes.
