### ISSUE TITLE
Bot Name & API Info

### ISSUE THREAD

**Issue by Timmooo** [FormalHellhound/BruhBot#26]
I feel bot name should be a modifiable option if multiple people will be using this - or is this specified by the API auth? I haven't registered at this stage

In regards to API auth I think this should be part of the config file and referenced for ease of change. 
This could be useful if we are wanting to each do testing and using our own version of the bot (just change command char). 

More importantly is if other people wanted to use it at some stage it makes it more user-friendly.

**Comment by MadnessExpress** [comment]
It is specified by the api auth, but you can assign nicknames to bots as a server admin, but it seems to break cleverbot functionality. I believe my bot's cleverbot plugin should still work if it is given a nickname.
