### ISSUE TITLE
Raw / Eval / System Admin Command

### ISSUE THREAD

**Issue by Timmooo** [FormalHellhound/BruhBot#27]
For when you are lazy and really don't want to login to your shell.
This command would let super users / admins send some text directly to the shell / system, run it, and return the results. Obviously, would only work with commands that don't require input.

!raw chmod 775 -R /home/tim/bruhbot/
Or something like that. Could also be fun for things like !raw date

More relevantly to this process could be for more complex git actions or forcing a bot restart etc.

**Comment by MadnessExpress** [comment]
This would be dangerous for inexperienced users, and could lead to their own servers being compromised if the wrong things are adjusted, so I will not include it in my source. There is an example of how to implement this on the discordrb github page for anyone interested. I don't want to be responsible for issue that arise from it.
