### ISSUE TITLE
Level Ups

### ISSUE THREAD

**Issue by Esjitu** [FormalHellhound/BruhBot#29]
Level up plugins seem to be growing in popularity with Discord bots, but most of the ones I've tried are rather annoying and spammy with their 'CONGRATS USER YOU'VE REACHED LEVEL [X]' messages, especially in active channels. 

So what about, instead of spammy notifications, we instead implement a `!level @username` command where you can check the given user's level on command, instead of needing to be constantly updated, or requiring an external web dashboard for a leaderboard (which is what Mee6 and Tatsumaki have). The config file could also allow owners to control which roles have the ability to run the `!level` command - either let all users do it so they can keep track of their own levels, or restrict it to staff so users won't be encouraged to shitpost simply to increase their e-peen. 

A core component of the function would be the ability to automatically assign roles to users when they reach specific post milestones. Say you want newcomers to land in a `#welcome` channel and keep your main channels off-limits until that user has proven themselves not to be a spammer, lurker, or other undesirable type. You would be able to set the bot to promote a user when they reach, say, 30 posts in the `#welcome` channel, and deliver a message (either in the channel or, preferably, via DM) that tells them `congratulations, @username, you've unlocked #channel!!` rather than actually giving them a raw 'you reached [x] level' notification. So this command would be a useful moderation utility for controlling permissions and not just a 'for fun' plugin.

**Comment by MadnessExpress** [comment]
This has been fully implemented with the latest commit.
