### ISSUE TITLE
Twitch Notification

### ISSUE THREAD

**Issue by Esjitu** [FormalHellhound/BruhBot#30]
I know Discord has its own built-in stream functionality, where, if you're streaming and have Discord open in Streamer Mode, it pops up a notification in the channel and says 'hey this person just started streaming go check it out!!'. But what if you're streaming, and you DON'T have Discord open on your computer? I typically don't - my games run better when I close out of unnecessary programs running in the background, so I'll use mobile if I'm in-game. Or, perhaps, you have a channel on your server where everyone is into a particular streamer (who is not part of your server) and you want to know when they come online.

Mee6 has this exact feature - where the bot owner can add a twitch username and have the bot announce when that user starts a stream, regardless of whether or not that user is part of your Discord server or has Discord running on their computer in Streamer Mode. So it must be possible somehow.

**Comment by MadnessExpress** [comment]
This has been implemented with the twitch_notifications plugin.
