### ISSUE TITLE
Lottery

### ISSUE THREAD

**Issue by Esjitu** [FormalHellhound/BruhBot#4]
Inspired by Bot-chan.

![bruhbot2](https://cloud.githubusercontent.com/assets/3802749/15586778/2a072d10-2354-11e6-9f2b-f631268e6d4e.png)

Allows users to enter themselves into a 'lottery' (that may either end after a set amount of time or on command). Once the users have entered, the winner is chosen, and a little message with some emoji fanfare announces the victor.

Not sure how Bot-chan does it, but it'd be best if only the lottery's creator is able to end it to avoid abuse. Otherwise, end the lottery after [x] amount of time passes.

**Comment by MadnessExpress** [comment]
This was implemented with the lotto command.
