### ISSUE TITLE
Rating

### ISSUE THREAD

**Issue by Esjitu** [FormalHellhound/BruhBot#9]
The ability to rate things - your laifu, other users, favorite foods, whatever - with `!rate [x]`. Rating should be on a scale of 1 to 10.

IMO it'd be more interesting for the rating number to be randomized, so every time I rate @username the bot could provide a different rating, rather than have it be set so @username is always a 7/10 no matter how many times I run the command.

Bonus points for sassy flavor text depending on the number given, ex. a rating of `1` might return a disparaging remark instead of simply saying `I give [x] a 1/10`.

**Comment by MadnessExpress** [comment]
This is done with the implementation of !rate, but sassy text is not implemented yet. I will mark this as closed, but tag with could use improvements.
